### ISSUE TITLE
NumberFormatException inside FirefoxWebElement.getSize()

### ISSUE THREAD

**Issue by chrsmith** [chrsmith/selenium-test#1]
Original [issue 1](https://code.google.com/p/selenium/issues/detail?id=1) created by chrsmith on 2009-08-26T08:38:47.000Z:

affected version: 0.9.7089

java.lang.NumberFormatException: For input string: &quot;328.3999938964844&quot;
	at 
java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
	at java.lang.Integer.parseInt(Integer.java:456)
	at java.lang.Integer.parseInt(Integer.java:497)
	at 
org.openqa.selenium.firefox.FirefoxWebElement.getSize(FirefoxWebElement.java:
154)

**Comment by chrsmith** [comment]
Comment [#1](https://code.google.com/p/selenium/issues/detail?id=1#c1) originally posted by chrsmith on 2009-08-26T09:09:06.000Z:

Just committed a test for this (subversion revision 7146).

**Comment by chrsmith** [comment]
Comment [#2](https://code.google.com/p/selenium/issues/detail?id=1#c2) originally posted by chrsmith on 2009-08-26T09:13:40.000Z:

Just committed a fix (subversion revison 7147)

**Comment by chrsmith** [comment]
Comment [#3](https://code.google.com/p/selenium/issues/detail?id=1#c3) originally posted by chrsmith on 2011-09-21T01:50:32.000Z:

I had also get this exception once.
